import DefaultHead from "next/head";

export default function Head() {
    return <>
        <DefaultHead>
            <title>Comissão DFM</title>
            <meta charSet="UTF-8" />
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1 , maximum-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </DefaultHead>
    </>
}